#!/bin/bash

proj="lucid"
svnroot="http://svn.linux-vserver.org/svn/${proj}"

usage() {
	echo "Usage: mkrelease"
}

die() {
	echo $1
	exit ${2:-1}
}

mkdir -p build &>/dev/null
pushd build &>/dev/null || die "popd failed"

cmake .. || die "cmake failed"
make doc || die "make doc failed"
make package_source || die "make package_source failed"
for i in *.tar.bz2 *.tar.gz; do md5sum $i > $i.md5; done

ver=$(grep CPACK_PACKAGE_VERSION CPackSourceConfig.cmake | sed 's/.*"\(.*\)".*/\1/g')

echo svn copy ${svnroot}/trunk ${svnroot}/tags/release-${ver} \
	-m "Tagging the ${ver} release of the ${proj} project" || die "svn copy failed"

popd &>/dev/null || die "popd failed"
